# Generated by Django 3.2.12 on 2022-04-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='owner',
        ),
    ]
