# Generated by Django 3.2.12 on 2022-04-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_text',
        ),
    ]
