# Generated by Django 3.2.12 on 2022-04-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='body',
        ),
    ]
