# Generated by Django 3.2.13 on 2022-04-23 09:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_comment_text_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.article_image_file_path),
        ),
    ]
