# Generated by Django 3.2.13 on 2022-05-09 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
